### ISSUE TITLE
joystickButton-example does not compile 

### ISSUE THREAD

**Issue by StefanL38** [dmadison/HID_Buttons#9]
I have installed the HID_Buttons-library through the library-manager 
and then I tried to compile the democode given here
https://github.com/dmadison/HID_Buttons/blob/master/examples/Joystick/JoystickButton/JoystickButton.ino

I adjusted the board to arduino leonardo

It does not compile but spits out this error-message:

Rebecca-Poty-Joystick-Test.-001:86:14: error: 'class Joystick' has no member named 'setYAxis'
     Joystick.setYAxis(pos);
              ^~~~~~~~
Bibliothek HID_Buttons in Version 1.0.1 im Ordner: F:\MyPortable-PRgs\arduino1.8.13\portable\sketchbook\libraries\HID_Buttons  wird verwendet
Bibliothek Joystick in Version 1.0.0 im Ordner: F:\MyPortable-PRgs\arduino1.8.13\portable\sketchbook\libraries\Joystick  wird verwendet
exit status 1
no matching function for call to 'Joystick::Joystick()'

Guys do you - at least - test your code for common boards?
I let UltraEdit search in all files under scr to find "setXAxis"  no match at all!

I wish there would be a rating-button in Github to rate you zero stars

**Comment by dmadison** [comment]
You are not compiling the example. The example is `JoystickButton.ino`, your error shows that you are compiling `Rebecca-Poty-Joystick-Test`.

>I let UltraEdit search in all files under scr to find "setXAxis" no match at all!

Which also makes sense. This library is for *buttons*, not analog inputs. There are no functions to set the joystick's axes in this library. There are also no function calls to that effect in the example (as you would expect). You are not compiling the example which is why you're running into that error.

>no matching function for call to 'Joystick::Joystick()'

The example does not call the default constructor for `Joystick`. The main class for the [Joystick library as linked in the README](https://github.com/MHeironimus/ArduinoJoystickLibrary) is `Joystick_`, and the example calls the dedicated constructor [as seen here (latest release)](https://github.com/dmadison/HID_Buttons/blob/v1.0.1/examples/Joystick/JoystickButton/JoystickButton.ino#L35-L40):

```cpp
Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID, JOYSTICK_TYPE_GAMEPAD,
	10, 0,                  // Button Count, Hat Switch Count
	false, false, false,    // No X, Y, or Z axes
	false, false, false,    // No Rx, Ry, or Rz
	false, false,           // No rudder or throttle
	false, false, false);   // No accelerator, brake, or steering
```

Which, again, shows that you're not compiling the example and this library is not the source of your issues.

>Guys do you - at least - test your code for common boards?
>I let UltraEdit search in all files under scr to find "setXAxis" no match at all!
>
>I wish there would be a rating-button in Github to rate you zero stars

The repository contains [a continuous integration script](https://github.com/dmadison/HID_Buttons/blob/5dc4f5a93625ff38e09bb952f2ea1cea974092c0/.github/workflows/ci.yml) which checks that the examples compile after every commit. You can see from [the latest commit](https://github.com/dmadison/HID_Buttons/actions/runs/482870861) that the examples are compiling fine. I've also tested on my local machine and unsurprisingly have no issues.

You are way out of line. Name calling and throwing a fit is no way to get help, especially for a free and open source project where no one is obligated to help you anyways.

I'm locking this issue and blocking you. Go whinge somewhere else.
